# .readthedocs.yaml
# Read the Docs configuration file
# Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Python dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Documentation configuration
sphinx:
  configuration: docs/conf.py
